server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**, /menus/**, /orderStatuses/**
        - id: store
          uri: http://localhost:8082
          predicates:
            - Path=/orderDbs/**, /orderSts/**
        - id: pay
          uri: http://localhost:8083
          predicates:
            - Path=/payDbs/**, 
        - id: custom
          uri: http://localhost:8084
          predicates:
            - Path=, 
        - id: delivery
          uri: http://localhost:8085
          predicates:
            - Path=/delveries/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://order:8080
          predicates:
            - Path=/orders/**, /menus/**, /orderStatuses/**
        - id: store
          uri: http://store:8080
          predicates:
            - Path=/orderDbs/**, /orderSts/**
        - id: pay
          uri: http://pay:8080
          predicates:
            - Path=/payDbs/**, 
        - id: custom
          uri: http://custom:8080
          predicates:
            - Path=, 
        - id: delivery
          uri: http://delivery:8080
          predicates:
            - Path=/delveries/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
