apiVersion: apps/v1
kind: Deployment
metadata:
  name: store_mnt
  labels:
    app: store_mnt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store_mnt
  template:
    metadata:
      labels:
        app: store_mnt
    spec:
      containers:
        - name: store_mnt
          image: username/store_mnt:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
