apiVersion: apps/v1
kind: Deployment
metadata:
  name: Custumer
  labels:
    app: Custumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Custumer
  template:
    metadata:
      labels:
        app: Custumer
    spec:
      containers:
        - name: Custumer
          image: username/Custumer:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
